from __future__ import annotations

import argparse
from pathlib import Path

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp"}
CLASS_ALIASES = {
    "fall": "fall",
    "falls": "fall",
    "fallen": "fall",
    "not_fall": "not-fall",
    "not-fall": "not-fall",
    "normal": "not-fall",
    "no_fall": "not-fall",
    "nonfall": "not-fall",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate YOLO-ready training config and label lists from a split image dataset. "
            "This is intended for YOLO image classification training (yolov8-cls) where the dataset "
            "has class folders such as fall/ and not-fall/."
        )
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=Path("fall_dataset/splits"),
        help="Root folder containing train/val/test directories.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("fall_dataset/yolo"),
        help="Directory to write YOLO config and text lists.",
    )
    return parser.parse_args()


def canonical_label(name: str) -> str:
    normalized = name.strip().lower()
    return CLASS_ALIASES.get(normalized, normalized)


def collect_images(folder: Path) -> list[Path]:
    files = []
    if not folder.exists():
        return files
    for path in sorted(folder.rglob("*")):
        if path.is_file() and path.suffix.lower() in IMAGE_EXTS:
            files.append(path)
    return files


def write_list_file(output_path: Path, image_paths: list[Path], base_dir: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        for img in image_paths:
            try:
                rel = img.relative_to(base_dir)
            except ValueError:
                rel = img
            f.write(f"{rel.as_posix()}\n")


def ensure_valid_class_dirs(split_root: Path) -> list[str]:
    classes = []
    for split_name in ["train", "val", "test"]:
        split_dir = split_root / split_name
        if not split_dir.exists():
            continue
        for class_dir in sorted(split_dir.iterdir()):
            if class_dir.is_dir():
                label = canonical_label(class_dir.name)
                if label not in classes:
                    classes.append(label)
    if not classes:
        raise ValueError(f"No valid class folders found under {split_root}.")
    return classes


def main() -> int:
    args = parse_args()
    data_root = args.data_root.resolve()
    output_dir = args.output_dir.resolve()

    if not data_root.exists():
        raise FileNotFoundError(f"Data root not found: {data_root}")

    classes = ensure_valid_class_dirs(data_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build list files for train/val/test
    for split_name in ["train", "val", "test"]:
        split_dir = data_root / split_name
        if not split_dir.exists():
            continue
        image_paths = collect_images(split_dir)
        write_list_file(output_dir / f"{split_name}.txt", image_paths, data_root)

    # Build YAML for YOLO classification training
    train_path = (data_root / "train").resolve()
    val_path = (data_root / "val").resolve()
    test_path = (data_root / "test").resolve()

    def rel_path(path: Path) -> str:
        try:
            return path.relative_to(data_root.parent).as_posix()
        except ValueError:
            return path.as_posix()

    yaml_path = output_dir / "data.yaml"
    yaml_text = (
        "# Auto-generated by prepare_yolo_training.py\n"
        f"train: {rel_path(train_path)}\n"
        f"val: {rel_path(val_path)}\n"
        f"test: {rel_path(test_path)}\n"
        f"nc: {len(classes)}\n"
        f"names: {classes}\n"
    )
    yaml_path.write_text(yaml_text, encoding="utf-8")

    print(f"[INFO] Detected classes: {classes}")
    print(f"[INFO] Wrote YOLO config to: {yaml_path}")
    for split_name in ["train", "val", "test"]:
        file_path = output_dir / f"{split_name}.txt"
        if file_path.exists():
            count = sum(1 for _ in file_path.open("r", encoding="utf-8"))
            print(f"[INFO] {split_name}.txt: {count} images")

    print("\nExample training command:")
    print(
        "yolo task=classify train model=yolov8n-cls.pt data="
        + str(yaml_path).replace('\\', '/')
        + " epochs=50 imgsz=224"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
